### Get all Trainings by User
GET http://localhost:5000/users/Marc/trainings

### Get all Trainings by User & Team
GET http://localhost:5000/users/Marc/teams/ESCOLA PIA TERRASSA_infantil_b_Marc/trainings

### Get by Id [1/2]
GET http://localhost:5000/users/Marc/trainings/ESCOLA PIA TERRASSA_infantil_b_Marc_Marc_Terrassa_Cami de Can boada no nº_11_12_2024_18:00

### Get by Id [2/2]
GET http://localhost:5000/users/Marc/teams/ESCOLA PIA TERRASSA_infantil_b_Marc/trainings/ESCOLA PIA TERRASSA_infantil_b_Marc_Marc_Terrassa_Cami de Can boada no nº_11_12_2024_18:00

### Create training
POST http://localhost:5000/users/Marc/teams/ESCOLA PIA TERRASSA_infantil_b_Marc/trainings
Content-Type:application/json

{
  "city": "Ullastrell",
  "address": "Camí 8",
  "date": "02/02/2024",
  "hour": "22:30",
  "pitchZone": 2,
  "exercises": ["Conditioning 1", "Conditioning 2", "Conditioning 3"],
  "name": "Test"
}

### Update training 
PATCH http://localhost:5000/users/Marc/teams/ESCOLA%20PIA%20TERRASSA_infantil_a_Marc/trainings/ESCOLA%20PIA%20TERRASSA_infantil_a_Marc_Marc_Terrassa_Can%20Boada_28_04_2024_18:00_2
Content-Type:application/json

{
   "name": "2do entrenamiento del año",
   "exercises": ["Conditioning 1", "Conditioning 2", "Duels 1"]
}

### Delete training
DELETE http://localhost:5000/users/Marc/teams/ESCOLA PIA TERRASSA_infantil_b_Marc/trainings/ESCOLA PIA TERRASSA_infantil_b_Marc_Marc_Terrassa_Cami de Can boada no nº_11_12_2024_18:00
